In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns", None)
plt.style.use("seaborn-v0_8")
np.random.seed(42)

In [3]:
!unzip api_data_aadhar_biometric.zip
!unzip api_data_aadhar_demographic.zip
!unzip api_data_aadhar_enrolment.zip

'''enrol_df = pd.read_csv("../data/enrolment_data.csv")
demo_df  = pd.read_csv("../data/demographic_update_data.csv")
bio_df   = pd.read_csv("../data/biometric_update_data.csv")'''

Archive:  api_data_aadhar_biometric.zip
   creating: api_data_aadhar_biometric/
  inflating: api_data_aadhar_biometric/api_data_aadhar_biometric_0_500000.csv
  inflating: api_data_aadhar_biometric/api_data_aadhar_biometric_1000000_1500000.csv
  inflating: api_data_aadhar_biometric/api_data_aadhar_biometric_1500000_1861108.csv
  inflating: api_data_aadhar_biometric/api_data_aadhar_biometric_500000_1000000.csv
Archive:  api_data_aadhar_demographic.zip
   creating: api_data_aadhar_demographic/
  inflating: api_data_aadhar_demographic/api_data_aadhar_demographic_0_500000.csv
  inflating: api_data_aadhar_demographic/api_data_aadhar_demographic_1000000_1500000.csv
  inflating: api_data_aadhar_demographic/api_data_aadhar_demographic_1500000_2000000.csv
  inflating: api_data_aadhar_demographic/api_data_aadhar_demographic_2000000_2071700.csv
  inflating: api_data_aadhar_demographic/api_data_aadhar_demographic_500000_1000000.csv
Archive:  api_data_aadhar_enrolment.zip
   creating: api_data_aadhar_enrolment/
  inflating: api_data_aadhar_enrolment/api_data_aadhar_enrolment_0_500000.csv
  inflating: api_data_aadhar_enrolment/api_data_aadhar_enrolment_1000000_1006029.csv
  inflating: api_data_aadhar_enrolment/api_data_aadhar_enrolment_500000_1000000.csv

'enrol_df = pd.read_csv("../data/enrolment_data.csv")\ndemo_df  = pd.read_csv("../data/demographic_update_data.csv")\nbio_df   = pd.read_csv("../data/biometric_update_data.csv")'

In [4]:
import glob

In [5]:
import os
os.getcwd()

'/content'

In [6]:
import os
os.listdir("/content")

['.config',
 'api_data_aadhar_biometric.zip',
 'api_data_aadhar_enrolment.zip',
 'api_data_aadhar_demographic.zip',
 'api_data_aadhar_demographic',
 'api_data_aadhar_biometric',
 'api_data_aadhar_enrolment',
 'sample_data']

In [7]:
import os
os.listdir("/content/api_data_aadhar_enrolment")

['api_data_aadhar_enrolment_500000_1000000.csv',
 'api_data_aadhar_enrolment_0_500000.csv',
 'api_data_aadhar_enrolment_1000000_1006029.csv']

In [8]:
enrolment_files = glob.glob("/content/api_data_aadhar_enrolment/*.csv")
print(enrolment_files)

['/content/api_data_aadhar_enrolment/api_data_aadhar_enrolment_500000_1000000.csv', '/content/api_data_aadhar_enrolment/api_data_aadhar_enrolment_0_500000.csv', '/content/api_data_aadhar_enrolment/api_data_aadhar_enrolment_1000000_1006029.csv']

In [9]:
enrol_df = pd.concat(
    (pd.read_csv(file) for file in enrolment_files),
    ignore_index=True
)
print("Enrolment data shape:", enrol_df.shape)

Enrolment data shape: (1006029, 7)

In [10]:
demo_files = glob.glob("/content/api_data_aadhar_demographic/*.csv")
print(demo_files)

['/content/api_data_aadhar_demographic/api_data_aadhar_demographic_1000000_1500000.csv', '/content/api_data_aadhar_demographic/api_data_aadhar_demographic_1500000_2000000.csv', '/content/api_data_aadhar_demographic/api_data_aadhar_demographic_500000_1000000.csv', '/content/api_data_aadhar_demographic/api_data_aadhar_demographic_2000000_2071700.csv', '/content/api_data_aadhar_demographic/api_data_aadhar_demographic_0_500000.csv']

In [11]:
demo_df = pd.concat((pd.read_csv(file) for file in demo_files), ignore_index= True)
print("Demographic updates data shape", demo_df.shape)

Demographic updates data shape (2071700, 6)

In [12]:
biometric_files = glob.glob("/content/api_data_aadhar_biometric/*.csv")
print(biometric_files)

['/content/api_data_aadhar_biometric/api_data_aadhar_biometric_1500000_1861108.csv', '/content/api_data_aadhar_biometric/api_data_aadhar_biometric_1000000_1500000.csv', '/content/api_data_aadhar_biometric/api_data_aadhar_biometric_500000_1000000.csv', '/content/api_data_aadhar_biometric/api_data_aadhar_biometric_0_500000.csv']

In [13]:
biometric_df = pd.concat((pd.read_csv(file) for file in biometric_files), ignore_index= True)
print("Biometric updates data shape", biometric_df.shape)

Biometric updates data shape (1861108, 6)

In [14]:
enrol_df.head()

,date,state,district,pincode,age_0_5,age_5_17,age_18_greater
0,26-10-2025,Andhra Pradesh,Nalgonda,508004,0,1,0
1,26-10-2025,Andhra Pradesh,Nalgonda,508238,1,0,0
2,26-10-2025,Andhra Pradesh,Nalgonda,508278,1,0,0
3,26-10-2025,Andhra Pradesh,Nandyal,518432,0,1,0
4,26-10-2025,Andhra Pradesh,Nandyal,518543,1,0,0

In [15]:
demo_df.head()

         date       state    district  pincode  demo_age_5_17  demo_age_17_
0  01-11-2025  Puducherry    Karaikal   609603              0             4
1  01-11-2025  Puducherry    Karaikal   609605              0             3
2  01-11-2025  Puducherry    Karaikal   609606              0             5
3  01-11-2025  Puducherry  Puducherry   605011              2             6
4  01-11-2025  Puducherry  Puducherry   605111              0             1

In [16]:
biometric_df.head()

,date,state,district,pincode,bio_age_5_17,bio_age_17_
0,08-12-2025,Uttar Pradesh,Moradabad,244411,4,2
1,08-12-2025,Uttar Pradesh,Moradabad,244601,14,19
2,08-12-2025,Uttar Pradesh,Muzaffarnagar,251002,22,37
3,08-12-2025,Uttar Pradesh,Muzaffarnagar,251202,4,4
4,08-12-2025,Uttar Pradesh,Muzaffarnagar,251319,4,7

In [17]:
enrol_df.columns

Index(['date', 'state', 'district', 'pincode', 'age_0_5', 'age_5_17',
       'age_18_greater'],
      dtype='object')

In [18]:
enrol_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1006029 entries, 0 to 1006028
Data columns (total 7 columns):
 #   Column          Non-Null Count    Dtype
---  ------          --------------    -----
 0   date            1006029 non-null  object
 1   state           1006029 non-null  object
 2   district        1006029 non-null  object
 3   pincode         1006029 non-null  int64
 4   age_0_5         1006029 non-null  int64
 5   age_5_17        1006029 non-null  int64
 6   age_18_greater  1006029 non-null  int64
dtypes: int64(4), object(3)
memory usage: 53.7+ MB

In [19]:
demo_df.columns

Index(['date', 'state', 'district', 'pincode', 'demo_age_5_17',
       'demo_age_17_'],
      dtype='object')

In [20]:
demo_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2071700 entries, 0 to 2071699
Data columns (total 6 columns):
 #   Column         Dtype
---  ------         -----
 0   date           object
 1   state          object
 2   district       object
 3   pincode        int64
 4   demo_age_5_17  int64
 5   demo_age_17_   int64
dtypes: int64(3), object(3)
memory usage: 94.8+ MB

In [21]:
biometric_df.columns

Index(['date', 'state', 'district', 'pincode', 'bio_age_5_17', 'bio_age_17_'], dtype='object')

In [22]:
biometric_df.info

<bound method DataFrame.info of                date          state       district  pincode  bio_age_5_17  \
0        08-12-2025  Uttar Pradesh      Moradabad   244411             4
1        08-12-2025  Uttar Pradesh      Moradabad   244601            14
2        08-12-2025  Uttar Pradesh  Muzaffarnagar   251002            22
3        08-12-2025  Uttar Pradesh  Muzaffarnagar   251202             4
4        08-12-2025  Uttar Pradesh  Muzaffarnagar   251319             4
...             ...            ...            ...      ...           ...
1861103  19-09-2025          Delhi     West Delhi   110041           102
1861104  19-09-2025          Delhi     West Delhi   110043             8
1861105  19-09-2025          Delhi     West Delhi   110058             7
1861106  19-09-2025            Goa      North Goa   403102             1
1861107  19-09-2025            Goa      North Goa   403106             1

         bio_age_17_
0                  2
1                 19
2                 37
3                  4
4                  7
...              ...
1861103          100
1861104            5
1861105            5
1861106            0
1861107            0

[1861108 rows x 6 columns]>

In [23]:
def clean_columns(df):
    df.columns = (
        df.columns
        .str.strip()
        .str.lower()
        .str.replace(" ", "_")
    )
    return df

In [24]:
enrol_df = clean_columns(enrol_df)
demo_df  = clean_columns(demo_df)
biometric_df   = clean_columns(biometric_df)

In [34]:
enrol_df['date'] = pd.to_datetime(enrol_df['date'], errors='coerce')
demo_df['date']  = pd.to_datetime(demo_df['date'], errors='coerce')
biometric_df['date']   = pd.to_datetime(biometric_df['date'], errors='coerce')

In [48]:
enrol_df.isnull().sum()

date              0
state             0
district          0
pincode           0
age_0_5           0
age_5_17          0
age_18_greater    0
has_valid_date    0
dtype: int64

In [57]:
demo_df.isnull().sum()

date              1187968
state                   0
district                0
pincode                 0
demo_age_5_17           0
demo_age_17_            0
has_valid_date          0
dtype: int64

In [65]:
biometric_df.isnull().sum()

date              944100
state                  0
district               0
pincode                0
bio_age_5_17           0
bio_age_17_            0
has_valid_date         0
dtype: int64

In [58]:
enrol_df['date'] = pd.to_datetime(enrol_df['date'], errors='coerce')
enrol_df['has_valid_date'] = enrol_df['date'].notna().astype(int)

In [59]:
demo_df['date'] = pd.to_datetime(demo_df['date'], errors='coerce')
demo_df['has_valid_date'] = demo_df['date'].notna().astype(int)

In [62]:
biometric_df['date'] = pd.to_datetime(biometric_df['date'], errors='coerce')
biometric_df['has_valid_date'] = biometric_df['date'].notna().astype(int)

In [64]:
print("ENROLMENT NULLS\n", enrol_df.isna().sum(), "\n")
print("DEMOGRAPHIC NULLS\n", demo_df.isna().sum(), "\n")
print("BIOMETRIC NULLS\n", biometric_df.isna().sum())

ENROLMENT NULLS
 date              0
state             0
district          0
pincode           0
age_0_5           0
age_5_17          0
age_18_greater    0
has_valid_date    0
dtype: int64

DEMOGRAPHIC NULLS
 date              1187968
state                   0
district                0
pincode                 0
demo_age_5_17           0
demo_age_17_            0
has_valid_date          0
dtype: int64

BIOMETRIC NULLS
 date              944100
state                  0
district               0
pincode                0
bio_age_5_17           0
bio_age_17_            0
has_valid_date         0
dtype: int64

In [67]:
print("Valid-date rows:")
print("Enrolment:", enrol_df['has_valid_date'].sum())
print("Demographic:", demo_df['has_valid_date'].sum())
print("Biometric:", biometric_df['has_valid_date'].sum())

Valid-date rows:
Enrolment: 1006029
Demographic: 883732
Biometric: 917008

In [70]:
# Total rows
enrol_total = len(enrol_df)
demo_total  = len(demo_df)
biometric_total   = len(biometric_df)

# Valid-date rows
enrol_valid = enrol_df['has_valid_date'].sum()
demo_valid  = demo_df['has_valid_date'].sum()
biometric_valid   = biometric_df['has_valid_date'].sum()

# Percentage calculation
enrol_pct = (enrol_valid / enrol_total) * 100
demo_pct  = (demo_valid / demo_total) * 100
biometric_pct   = (biometric_valid / biometric_total) * 100

print(f"Enrolment:   {enrol_valid} / {enrol_total}  ({enrol_pct:.2f}%) valid-date records")
print(f"Demographic: {demo_valid} / {demo_total}   ({demo_pct:.2f}%) valid-date records")
print(f"Biometric:   {biometric_valid} / {biometric_total}    ({biometric_pct:.2f}%) valid-date records")

Enrolment:   1006029 / 1006029  (100.00%) valid-date records
Demographic: 883732 / 2071700   (42.66%) valid-date records
Biometric:   917008 / 1861108    (49.27%) valid-date records

In [71]:
enrol_df.describe()

,date,pincode,age_0_5,age_5_17,age_18_greater,has_valid_date
count,1006029,1.006029e+06,1.006029e+06,1.006029e+06,1.006029e+06,1006029.0
mean,2025-10-23 18:26:44.387150336,5.186415e+05,3.525709e+00,1.710074e+00,1.673441e-01,1.0
min,2025-03-02 00:00:00,1.000000e+05,0.000000e+00,0.000000e+00,0.000000e+00,1.0
25%,2025-09-19 00:00:00,3.636410e+05,1.000000e+00,0.000000e+00,0.000000e+00,1.0
50%,2025-10-27 00:00:00,5.174170e+05,2.000000e+00,0.000000e+00,0.000000e+00,1.0
75%,2025-11-15 00:00:00,7.001040e+05,3.000000e+00,1.000000e+00,0.000000e+00,1.0
max,2025-12-31 00:00:00,8.554560e+05,2.688000e+03,1.812000e+03,8.550000e+02,1.0
std,NaN,2.056360e+05,1.753851e+01,1.436963e+01,3.220525e+00,0.0

In [72]:
demo_df.describe()

,date,pincode,demo_age_5_17,demo_age_17_,has_valid_date
count,883732,2.071700e+06,2.071700e+06,2.071700e+06,2.071700e+06
mean,2025-06-23 14:14:09.466581504,5.278318e+05,2.347552e+00,2.144701e+01,4.265733e-01
min,2025-01-03 00:00:00,1.000000e+05,0.000000e+00,0.000000e+00,0.000000e+00
25%,2025-03-12 00:00:00,3.964690e+05,0.000000e+00,2.000000e+00,0.000000e+00
50%,2025-06-12 00:00:00,5.243220e+05,1.000000e+00,6.000000e+00,0.000000e+00
75%,2025-10-09 00:00:00,6.955070e+05,2.000000e+00,1.500000e+01,1.000000e+00
max,2025-12-12 00:00:00,8.554560e+05,2.690000e+03,1.616600e+04,1.000000e+00
std,NaN,1.972933e+05,1.490355e+01,1.252498e+02,4.945793e-01

In [73]:
biometric_df.describe()

,date,pincode,bio_age_5_17,bio_age_17_,has_valid_date
count,917008,1.861108e+06,1.861108e+06,1.861108e+06,1.861108e+06
mean,2025-06-05 20:55:16.870518272,5.217612e+05,1.839058e+01,1.909413e+01,4.927215e-01
min,2025-01-03 00:00:00,1.100010e+05,0.000000e+00,0.000000e+00,0.000000e+00
25%,2025-02-12 00:00:00,3.911750e+05,1.000000e+00,1.000000e+00,0.000000e+00
50%,2025-06-09 00:00:00,5.224010e+05,3.000000e+00,4.000000e+00,0.000000e+00
75%,2025-09-12 00:00:00,6.866362e+05,1.100000e+01,1.000000e+01,1.000000e+00
max,2025-12-12 00:00:00,8.554560e+05,8.002000e+03,7.625000e+03,1.000000e+00
std,NaN,1.981627e+05,8.370421e+01,8.806502e+01,4.999472e-01

In [74]:
enrol_df['state'].nunique()

55

In [75]:
enrol_df['district'].nunique()

985

In [76]:
enrol_df['pincode'].nunique()

19463

In [77]:
demo_df['state'].nunique()

65

In [78]:
demo_df['district'].nunique()

983

In [79]:
demo_df['pincode'].nunique()

19742

In [80]:
biometric_df['state'].nunique()

57

In [81]:
biometric_df['district'].nunique()

974

In [82]:
biometric_df['pincode'].nunique()

19707

In [83]:
sorted(enrol_df['state'].unique())[:20]

['100000',
 'Andaman & Nicobar Islands',
 'Andaman and Nicobar Islands',
 'Andhra Pradesh',
 'Arunachal Pradesh',
 'Assam',
 'Bihar',
 'Chandigarh',
 'Chhattisgarh',
 'Dadra & Nagar Haveli',
 'Dadra and Nagar Haveli',
 'Dadra and Nagar Haveli and Daman and Diu',
 'Daman & Diu',
 'Daman and Diu',
 'Delhi',
 'Goa',
 'Gujarat',
 'Haryana',
 'Himachal Pradesh',
 'Jammu & Kashmir']

In [86]:
def flag_numeric_locations(df):
    df['state_is_numeric'] = df['state'].str.isnumeric()
    df['district_is_numeric'] = df['district'].str.isnumeric()
    return df

In [87]:
enrol_df = flag_numeric_locations(enrol_df)
demo_df  = flag_numeric_locations(demo_df)
bio_df   = flag_numeric_locations(biometric_df)

In [88]:
print("Numeric state counts:")
print("Enrolment:", enrol_df['state_is_numeric'].sum())
print("Demographic:", demo_df['state_is_numeric'].sum())
print("Biometric:", bio_df['state_is_numeric'].sum())

print("\nNumeric district counts:")
print("Enrolment:", enrol_df['district_is_numeric'].sum())
print("Demographic:", demo_df['district_is_numeric'].sum())
print("Biometric:", bio_df['district_is_numeric'].sum())

Numeric state counts:
Enrolment: 22
Demographic: 2
Biometric: 0

Numeric district counts:
Enrolment: 22
Demographic: 2
Biometric: 0

In [89]:
enrol_df.loc[enrol_df['state_is_numeric'], ['state', 'district']].head()

         state district
262744  100000   100000
280936  100000   100000
291621  100000   100000
323985  100000   100000
361631  100000   100000

In [93]:
def clean_location_columns(df):
    # State cleaning
    df['state_clean'] = (
        df['state']
        .astype(str)
        .str.strip()
        .str.title()
    )

    # District cleaning
    df['district_clean'] = (
        df['district']
        .astype(str)
        .str.strip()
        .str.title()
    )

    # Mark numeric contamination
    df['state_is_numeric'] = df['state_clean'].str.isnumeric()
    df['district_is_numeric'] = df['district_clean'].str.isnumeric()

    # Replace numeric-only entries with NaN in clean columns
    df.loc[df['state_is_numeric'], 'state_clean'] = pd.NA
    df.loc[df['district_is_numeric'], 'district_clean'] = pd.NA

    return df

In [96]:
enrol_df = clean_location_columns(enrol_df)
demo_df  = clean_location_columns(demo_df)
bio_df   = clean_location_columns(bio_df)

In [97]:
def mark_valid_location(df):
    df['valid_location'] = (
        df['state_clean'].notna() &
        df['district_clean'].notna()
    )
    return df

In [98]:
enrol_df = mark_valid_location(enrol_df)
demo_df  = mark_valid_location(demo_df)
bio_df   = mark_valid_location(bio_df)

In [99]:
print("Invalid location rows:")
print("Enrolment:", (~enrol_df['valid_location']).sum())
print("Demographic:", (~demo_df['valid_location']).sum())
print("Biometric:", (~bio_df['valid_location']).sum())

Invalid location rows:
Enrolment: 22
Demographic: 2
Biometric: 0

In [100]:
enrol_df.loc[~enrol_df['valid_location'], ['state', 'district']].head(10)

         state district
262744  100000   100000
280936  100000   100000
291621  100000   100000
323985  100000   100000
361631  100000   100000
414457  100000   100000
429221  100000   100000
447831  100000   100000
459114  100000   100000
460973  100000   100000

In [102]:
import re
def normalize_state_name(state):
    """
    Standardizes Indian state/UT names by:
    - Lowercasing
    - Replacing '&' with 'and'
    - Removing extra spaces
    """
    if pd.isna(state):
        return pd.NA

    state = state.lower().strip()
    state = state.replace("&", "and")
    state = " ".join(state.split())

    return state

In [103]:
for df in [enrol_df, demo_df, biometric_df]:
    df['state_norm'] = df['state'].apply(normalize_state_name)

In [104]:
STATE_CANONICAL_MAP = {
    # Andaman & Nicobar
    "andaman and nicobar islands": "Andaman and Nicobar Islands",

    # Dadra & Nagar Haveli / Daman & Diu
    "dadra and nagar haveli": "Dadra and Nagar Haveli and Daman and Diu",
    "daman and diu": "Dadra and Nagar Haveli and Daman and Diu",
    "dadra and nagar haveli and daman and diu": "Dadra and Nagar Haveli and Daman and Diu",

    # Jammu & Kashmir / Ladakh
    "jammu and kashmir": "Jammu and Kashmir",

    # Delhi
    "delhi": "Delhi",

    # Puducherry
    "pondicherry": "Puducherry",

    # Odisha
    "orissa": "Odisha"
}

In [105]:
def apply_canonical_mapping(state):
    if pd.isna(state):
        return pd.NA
    return STATE_CANONICAL_MAP.get(state, state.title())

In [106]:
for df in [enrol_df, demo_df, biometric_df]:
    df['state_clean'] = df['state_norm'].apply(apply_canonical_mapping)

In [107]:
print("Unique states after cleaning:")
print("Enrolment:", enrol_df['state_clean'].nunique())
print("Demographic:", demo_df['state_clean'].nunique())
print("Biometric:", biometric_df['state_clean'].nunique())

Unique states after cleaning:
Enrolment: 40
Demographic: 49
Biometric: 41

In [109]:
def find_suspicious_states(df, name):
    print(f"\nSuspicious states in {name}:")
    suspicious = (
        df['state_clean']
        .dropna()
        .loc[df['state_clean'].str.contains(r'\d', regex=True)]
        .unique()
    )
    print(suspicious[:20], " ... total:", len(suspicious))


find_suspicious_states(enrol_df, "Enrolment")
find_suspicious_states(demo_df, "Demographic")
find_suspicious_states(biometric_df, "Biometric")

Suspicious states in Enrolment:
['100000']  ... total: 1

Suspicious states in Demographic:
['100000']  ... total: 1

Suspicious states in Biometric:
[]  ... total: 0

In [110]:
def is_valid_state_name(state):
    if pd.isna(state):
        return False
    if any(char.isdigit() for char in state):
        return False
    return True

In [111]:
for df in [enrol_df, demo_df, biometric_df]:
    df['valid_state'] = df['state_clean'].apply(is_valid_state_name)

In [112]:
print("Valid unique states only:")
print("Enrolment:", enrol_df.loc[enrol_df['valid_state'], 'state_clean'].nunique())
print("Demographic:", demo_df.loc[demo_df['valid_state'], 'state_clean'].nunique())
print("Biometric:", biometric_df.loc[biometric_df['valid_state'], 'state_clean'].nunique())

Valid unique states only:
Enrolment: 39
Demographic: 48
Biometric: 41

In [113]:
for df in [enrol_df, demo_df, biometric_df]:
    df['analysis_ready'] = (
        df['has_valid_date'] &
        df['valid_state'] &
        df['valid_location']  # district + state both valid
    )

In [114]:
print("Final ANALYSIS-READY unique states:")
print("Enrolment:", enrol_df.loc[enrol_df['analysis_ready'], 'state_clean'].nunique())
print("Demographic:", demo_df.loc[demo_df['analysis_ready'], 'state_clean'].nunique())
print("Biometric:", biometric_df.loc[biometric_df['analysis_ready'], 'state_clean'].nunique())

Final ANALYSIS-READY unique states:
Enrolment: 39
Demographic: 40
Biometric: 40

In [115]:
def inspect_district_issues(df, name):
    print(f"\n{name} district sample:")
    print(df['district'].value_counts().head(10))
    print("Unique districts:", df['district'].nunique())

In [116]:
inspect_district_issues(enrol_df, "Enrolment")
inspect_district_issues(demo_df, "Demographic")
inspect_district_issues(biometric_df, "Biometric")

Enrolment district sample:
district
Pune                 6663
North 24 Parganas    6488
Barddhaman           5362
Bengaluru            5305
Hyderabad            4984
Malappuram           4700
Jaipur               4670
Murshidabad          4562
South 24 Parganas    4559
K.v. Rangareddy      4550
Name: count, dtype: int64
Unique districts: 985

Demographic district sample:
district
North 24 Parganas    12994
Pune                 12450
Barddhaman           12349
East Godavari        12186
Thrissur             12097
Karimnagar           10045
Hyderabad            10010
West Godavari        10007
Ernakulam             9895
Warangal              9857
Name: count, dtype: int64
Unique districts: 983

Biometric district sample:
district
Pune                 11586
Thrissur             11165
East Godavari        10647
North 24 Parganas    10595
Barddhaman           10545
Warangal              9976
Palakkad              9605
Karimnagar            9514
Hyderabad             9422
Ernakulam             9113
Name: count, dtype: int64
Unique districts: 974

In [132]:
def normalize_district_name(district):
    if pd.isna(district):
        return pd.NA

    district = district.lower().strip()
    district = district.replace("&", "and")
    district = " ".join(district.split())

    return district

In [133]:
for df in [enrol_df, demo_df, biometric_df]:
    df['district_norm'] = df['district'].apply(normalize_district_name)

In [134]:
def is_valid_district_name(district):
    if pd.isna(district):
        return False
    if any(char.isdigit() for char in district):
        return False
    return True

In [135]:
for df in [enrol_df, demo_df, biometric_df]:
    df['valid_district'] = df['district_norm'].apply(is_valid_district_name)

In [136]:
print("Invalid district rows:")
print("Enrolment:", (~enrol_df['valid_district']).sum())
print("Demographic:", (~demo_df['valid_district']).sum())
print("Biometric:", (~biometric_df['valid_district']).sum())

Invalid district rows:
Enrolment: 11104
Demographic: 21009
Biometric: 17207

In [137]:
for df in [enrol_df, demo_df, biometric_df]:
    df['district_clean'] = df['district_norm'].where(df['valid_district'], pd.NA)

In [138]:
for df in [enrol_df, demo_df, biometric_df]:
    df['analysis_ready'] = (
        df['has_valid_date'] &
        df['valid_state'] &
        df['valid_district']
    )

In [139]:
print("Final ANALYSIS-READY unique districts:")
print("Enrolment:", enrol_df.loc[enrol_df['analysis_ready'], 'district_clean'].nunique())
print("Demographic:", demo_df.loc[demo_df['analysis_ready'], 'district_clean'].nunique())
print("Biometric:", biometric_df.loc[biometric_df['analysis_ready'], 'district_clean'].nunique())

Final ANALYSIS-READY unique districts:
Enrolment: 956
Demographic: 931
Biometric: 937

In [140]:
# Create final analysis-ready datasets
final_enrol_df = enrol_df.loc[enrol_df['analysis_ready']].copy()
final_demo_df  = demo_df.loc[demo_df['analysis_ready']].copy()
final_bio_df   = biometric_df.loc[biometric_df['analysis_ready']].copy()

# Export to CSV (no index)
final_enrol_df.to_csv("clean_enrolment_base.csv", index=False)
final_demo_df.to_csv("clean_demographic_base.csv", index=False)
final_bio_df.to_csv("clean_biometric_base.csv", index=False)

print("Export complete:")
print(" - clean_enrolment_base.csv")
print(" - clean_demographic_base.csv")
print(" - clean_biometric_base.csv")

Export complete:
 - clean_enrolment_base.csv
 - clean_demographic_base.csv
 - clean_biometric_base.csv

In [141]:
print("Enrolment columns:")
print(final_enrol_df.columns.tolist())

print("\nDemographic columns:")
print(final_demo_df.columns.tolist())

print("\nBiometric columns:")
print(final_bio_df.columns.tolist())

Enrolment columns:
['date', 'state', 'district', 'pincode', 'age_0_5', 'age_5_17', 'age_18_greater', 'has_valid_date', 'state_is_numeric', 'district_is_numeric', 'state_clean', 'district_clean', 'valid_location', 'state_norm', 'valid_state', 'analysis_ready', 'district_norm', 'valid_district']

Demographic columns:
['date', 'state', 'district', 'pincode', 'demo_age_5_17', 'demo_age_17_', 'has_valid_date', 'state_is_numeric', 'district_is_numeric', 'state_clean', 'district_clean', 'valid_location', 'state_norm', 'valid_state', 'analysis_ready', 'district_norm', 'valid_district']

Biometric columns:
['date', 'state', 'district', 'pincode', 'bio_age_5_17', 'bio_age_17_', 'has_valid_date', 'state_is_numeric', 'district_is_numeric', 'state_clean', 'district_clean', 'valid_location', 'state_norm', 'valid_state', 'analysis_ready', 'district_norm', 'valid_district']

In [143]:
for df, name in zip([final_enrol_df, final_demo_df, final_bio_df],
                    ["Enrolment", "Demographic", "Biometric"]):
    total = len(df)
    valid = df['has_valid_date'].sum()
    print(f"{name}: {valid} valid dates / {total} total rows → {(valid/total)*100:.2f}% valid")

Enrolment: 994925 valid dates / 994925 total rows → 100.00% valid
Demographic: 874647 valid dates / 874647 total rows → 100.00% valid
Biometric: 908286 valid dates / 908286 total rows → 100.00% valid

In [144]:
for df, name in zip([enrol_df, demo_df, biometric_df],
                    ["Enrolment", "Demographic", "Biometric"]):
    total_rows = len(df)
    valid_rows = df['has_valid_date'].sum()
    removed = total_rows - valid_rows
    print(f"{name}: {removed} rows removed due to invalid/missing dates")

Enrolment: 0 rows removed due to invalid/missing dates
Demographic: 1187968 rows removed due to invalid/missing dates
Biometric: 944100 rows removed due to invalid/missing dates

In [145]:
enrolment_final_cols = [
    'date',
    'state_clean',
    'district_clean',
    'pincode',
    'age_0_5',
    'age_5_17',
    'age_18_greater'
]

enrolment_final = final_enrol_df[enrolment_final_cols].copy()

In [146]:
demographic_final_cols = [
    'date',
    'state_clean',
    'district_clean',
    'pincode',
    'demo_age_5_17',
    'demo_age_17_'
]

demographic_final = final_demo_df[demographic_final_cols].copy()

In [147]:
biometric_final_cols = [
    'date',
    'state_clean',
    'district_clean',
    'pincode',
    'bio_age_5_17',
    'bio_age_17_'
]

biometric_final = final_bio_df[biometric_final_cols].copy()

In [151]:
enrolment_final = final_enrol_df[enrolment_final_cols].copy()
demographic_final = final_demo_df[demographic_final_cols].copy()
biometric_final = final_bio_df[biometric_final_cols].copy()

In [152]:
# Export to CSV (no index)
enrolment_final.to_csv("clean_enrolment_base.csv", index=False)
demographic_final.to_csv("clean_demographic_base.csv", index=False)
biometric_final.to_csv("clean_biometric_base.csv", index=False)

print("Export complete:")
print(" - clean_enrolment_base.csv")
print(" - clean_demographic_base.csv")
print(" - clean_biometric_base.csv")

Export complete:
 - clean_enrolment_base.csv
 - clean_demographic_base.csv
 - clean_biometric_base.csv

In [153]:
print("Enrolment sample:")
display(enrolment_final.head(30))

print("Demographic sample:")
display(demographic_final.head(30))

print("Biometric sample:")
display(biometric_final.head(30))

Enrolment sample:

,date,state_clean,district_clean,pincode,age_0_5,age_5_17,age_18_greater
0,2025-10-26,Andhra Pradesh,nalgonda,508004,0,1,0
1,2025-10-26,Andhra Pradesh,nalgonda,508238,1,0,0
2,2025-10-26,Andhra Pradesh,nalgonda,508278,1,0,0
3,2025-10-26,Andhra Pradesh,nandyal,518432,0,1,0
4,2025-10-26,Andhra Pradesh,nandyal,518543,1,0,0
5,2025-10-26,Andhra Pradesh,nellore,524003,0,1,0
6,2025-10-26,Andhra Pradesh,nellore,524129,2,0,0
7,2025-10-26,Andhra Pradesh,nellore,524132,3,0,0
8,2025-10-26,Andhra Pradesh,nellore,524230,1,0,0
9,2025-10-26,Andhra Pradesh,nellore,524302,1,0,0
10,2025-10-26,Andhra Pradesh,nellore,524315,0,1,0
11,2025-10-26,Andhra Pradesh,nizamabad,503003,1,0,0
12,2025-10-26,Andhra Pradesh,palnadu,522410,1,0,0
13,2025-10-26,Andhra Pradesh,prakasam,523246,0,1,0
14,2025-10-26,Andhra Pradesh,prakasam,523265,1,0,0
15,2025-10-26,Andhra Pradesh,prakasam,523327,2,1,0
16,2025-10-26,Andhra Pradesh,rangareddi,500048,1,0,0
17,2025-10-26,Andhra Pradesh,rangareddi,501401,0,1,0
18,2025-10-26,Andhra Pradesh,sri potti sriramulu nellore,524313,0,1,0
19,2025-10-26,Andhra Pradesh,sri potti sriramulu nellore,524322,1,1,0
20,2025-10-26,Andhra Pradesh,sri sathya sai,515671,3,0,0
21,2025-10-26,Andhra Pradesh,srikakulam,532185,2,0,0
22,2025-10-26,Andhra Pradesh,srikakulam,532221,1,0,0
23,2025-10-26,Andhra Pradesh,srikakulam,532407,1,0,0
24,2025-10-26,Andhra Pradesh,srikakulam,532459,1,0,0
25,2025-10-26,Andhra Pradesh,srikakulam,532484,1,0,0
26,2025-10-26,Andhra Pradesh,srikakulam,535557,1,0,0
27,2025-10-26,Andhra Pradesh,tirupati,524126,1,0,0
28,2025-10-26,Andhra Pradesh,visakhapatnam,530016,1,0,0
29,2025-10-26,Andhra Pradesh,visakhapatnam,530018,2,0,0

Demographic sample:

,date,state_clean,district_clean,pincode,demo_age_5_17,demo_age_17_
0,2025-01-11,Puducherry,karaikal,609603,0,4
1,2025-01-11,Puducherry,karaikal,609605,0,3
2,2025-01-11,Puducherry,karaikal,609606,0,5
3,2025-01-11,Puducherry,puducherry,605011,2,6
4,2025-01-11,Puducherry,puducherry,605111,0,1
5,2025-01-11,Puducherry,puducherry,673310,1,5
6,2025-01-11,Puducherry,yanam,533464,0,1
7,2025-01-11,Punjab,amritsar,143001,22,217
8,2025-01-11,Punjab,amritsar,143002,0,8
9,2025-01-11,Punjab,amritsar,143022,0,16
10,2025-01-11,Punjab,amritsar,143105,1,56
11,2025-01-11,Punjab,amritsar,143107,0,11
12,2025-01-11,Punjab,amritsar,143110,1,21
13,2025-01-11,Punjab,amritsar,143114,0,9
14,2025-01-11,Punjab,amritsar,143204,0,2
15,2025-01-11,Punjab,amritsar,143603,0,22
16,2025-01-11,Punjab,barnala,148025,1,4
17,2025-01-11,Punjab,bathinda,151001,6,69
18,2025-01-11,Punjab,bathinda,151101,4,16
19,2025-01-11,Punjab,bathinda,151103,2,25
20,2025-01-11,Punjab,bathinda,151105,0,4
21,2025-01-11,Punjab,bathinda,151106,0,6
22,2025-01-11,Punjab,bathinda,151301,3,22
23,2025-01-11,Punjab,faridkot,151202,0,16
24,2025-01-11,Punjab,faridkot,151204,3,36
25,2025-01-11,Punjab,faridkot,151205,0,9
26,2025-01-11,Punjab,fatehgarh sahib,140407,0,1
27,2025-01-11,Punjab,fatehgarh sahib,140412,1,16
28,2025-01-11,Punjab,fazilka,152121,0,7
29,2025-01-11,Punjab,fazilka,152124,0,13

Biometric sample:

,date,state_clean,district_clean,pincode,bio_age_5_17,bio_age_17_
0,2025-08-12,Uttar Pradesh,moradabad,244411,4,2
1,2025-08-12,Uttar Pradesh,moradabad,244601,14,19
2,2025-08-12,Uttar Pradesh,muzaffarnagar,251002,22,37
3,2025-08-12,Uttar Pradesh,muzaffarnagar,251202,4,4
4,2025-08-12,Uttar Pradesh,muzaffarnagar,251319,4,7
5,2025-08-12,Uttar Pradesh,pilibhit,262001,116,94
6,2025-08-12,Uttar Pradesh,pilibhit,262121,13,15
7,2025-08-12,Uttar Pradesh,pilibhit,262124,6,9
8,2025-08-12,Uttar Pradesh,pratapgarh,229408,1,3
9,2025-08-12,Uttar Pradesh,pratapgarh,230001,7,8
10,2025-08-12,Uttar Pradesh,pratapgarh,230128,7,9
11,2025-08-12,Uttar Pradesh,pratapgarh,230129,4,9
12,2025-08-12,Uttar Pradesh,pratapgarh,230144,7,4
13,2025-08-12,Uttar Pradesh,pratapgarh,230204,13,22
14,2025-08-12,Uttar Pradesh,pratapgarh,230404,2,3
15,2025-08-12,Uttar Pradesh,prayagraj,211015,0,1
16,2025-08-12,Uttar Pradesh,prayagraj,212106,1,1
17,2025-08-12,Uttar Pradesh,prayagraj,212202,2,0
18,2025-08-12,Uttar Pradesh,prayagraj,212307,2,1
19,2025-08-12,Uttar Pradesh,prayagraj,221508,0,3
20,2025-08-12,Uttar Pradesh,rae bareli,229125,7,9
21,2025-08-12,Uttar Pradesh,rae bareli,229126,2,0
22,2025-08-12,Uttar Pradesh,rae bareli,229215,0,3
23,2025-08-12,Uttar Pradesh,rae bareli,229303,15,17
24,2025-08-12,Uttar Pradesh,rampur,244925,16,24
25,2025-08-12,Uttar Pradesh,saharanpur,247340,16,11
26,2025-08-12,Uttar Pradesh,saharanpur,247451,29,26
27,2025-08-12,Uttar Pradesh,saharanpur,247554,40,46
28,2025-08-12,Uttar Pradesh,sambhal,202412,21,13
29,2025-08-12,Uttar Pradesh,sambhal,202414,16,3

In [154]:
import os

files = ["clean_enrolment_base.csv", "clean_demographic_base.csv", "clean_biometric_base.csv"]

for f in files:
    if os.path.exists(f):
        size_mb = os.path.getsize(f) / (1024*1024)
        print(f"{f} exists, size: {size_mb:.2f} MB")
    else:
        print(f"{f} NOT FOUND!")

clean_enrolment_base.csv exists, size: 42.23 MB
clean_demographic_base.csv exists, size: 36.06 MB
clean_biometric_base.csv exists, size: 37.59 MB

In [156]:

enrol_check = pd.read_csv("clean_enrolment_base.csv")
demo_check = pd.read_csv("clean_demographic_base.csv")
bio_check  = pd.read_csv("clean_biometric_base.csv")


print("Row counts:")
print("Enrolment:", len(enrol_check))
print("Demographic:", len(demo_check))
print("Biometric:", len(bio_check))

Row counts:
Enrolment: 994925
Demographic: 874647
Biometric: 908286

In [157]:
print("Column names verification:")
print("Enrolment:", enrol_check.columns.tolist())
print("Demographic:", demo_check.columns.tolist())
print("Biometric:", bio_check.columns.tolist())

Column names verification:
Enrolment: ['date', 'state_clean', 'district_clean', 'pincode', 'age_0_5', 'age_5_17', 'age_18_greater']
Demographic: ['date', 'state_clean', 'district_clean', 'pincode', 'demo_age_5_17', 'demo_age_17_']
Biometric: ['date', 'state_clean', 'district_clean', 'pincode', 'bio_age_5_17', 'bio_age_17_']

In [158]:
print("Enrolment stats:")
display(enrol_check.describe())

print("Demographic stats:")
display(demo_check.describe())

print("Biometric stats:")
display(bio_check.describe())

Enrolment stats:

             pincode        age_0_5       age_5_17  age_18_greater
count  994925.000000  994925.000000  994925.000000   994925.000000
mean   516327.986734       3.514702       1.712573        0.166796
std    205571.461874      17.592445      14.426511        3.229915
min    110001.000000       0.000000       0.000000        0.000000
25%    362275.000000       1.000000       0.000000        0.000000
50%    516107.000000       2.000000       0.000000        0.000000
75%    695009.000000       3.000000       1.000000        0.000000
max    855456.000000    2688.000000    1812.000000      855.000000

Demographic stats:

             pincode  demo_age_5_17   demo_age_17_
count  874647.000000  874647.000000  874647.000000
mean   527174.776318       3.719416      32.886745
std    197145.635663      22.634077     189.159023
min    110001.000000       0.000000       0.000000
25%    396193.000000       0.000000       2.000000
50%    524315.000000       1.000000       6.000000
75%    691523.000000       2.000000      17.000000
max    855456.000000    2690.000000   16166.000000

Biometric stats:

            pincode   bio_age_5_17    bio_age_17_
count  908286.00000  908286.000000  908286.000000
mean   521166.50813      29.315932      31.439877
std    198290.71234     117.534534     124.020817
min    110001.00000       0.000000       0.000000
25%    390007.00000       1.000000       2.000000
50%    522257.00000       4.000000       5.000000
75%    686018.00000      15.000000      14.000000
max    855456.00000    8002.000000    7625.000000

In [159]:
print("Unique states/districts after export:")

for df, name in zip([enrol_check, demo_check, bio_check], ["Enrolment", "Demographic", "Biometric"]):
    print(f"{name}:")
    print("States:", df['state_clean'].nunique())
    print("Districts:", df['district_clean'].nunique())

Unique states/districts after export:
Enrolment:
States: 39
Districts: 956
Demographic:
States: 40
Districts: 931
Biometric:
States: 40
Districts: 937

In [175]:
for df, name in zip([enrol_check, demo_check, bio_check], ["Enrolment", "Demographic", "Biometric"]):
    print(f"Random sample from {name}:")
    display(df.sample(5))

Random sample from Enrolment:

,date,state_clean,district_clean,pincode,age_0_5,age_5_17,age_18_greater
556501,2025-09-04,Telangana,medak,502325,1,0,0
856108,2025-10-13,Uttar Pradesh,ghazipur,233310,1,0,0
660158,2025-09-12,Jammu and Kashmir,kathua,184204,1,1,0
889600,2025-10-16,Tamil Nadu,sivaganga,630302,3,0,0
570082,2025-09-06,Karnataka,hassan,573120,1,1,0

Random sample from Demographic:

,date,state_clean,district_clean,pincode,demo_age_5_17,demo_age_17_
557156,2025-04-12,Karnataka,belgaum,591201,0,4
484645,2025-10-11,Maharashtra,kolhapur,416235,0,45
570181,2025-08-12,Haryana,yamuna nagar,133103,1,19
259000,2025-05-12,Uttarakhand,tehri garhwal,249196,2,1
863392,2025-10-09,Uttar Pradesh,gonda,271319,4,10

Random sample from Biometric:

,date,state_clean,district_clean,pincode,bio_age_5_17,bio_age_17_
719711,2025-03-09,Delhi,west delhi,110041,84,122
29059,2025-10-12,Odisha,ganjam,760002,26,7
511198,2025-05-11,Tamil Nadu,tiruvallur,631302,5,4
445540,2025-02-11,Haryana,ambala,133006,3,1
603622,2025-01-05,Andhra Pradesh,nellore,524304,44,12

In [176]:
print("Total enrolments by age group:")
print(enrolment_final[['age_0_5','age_5_17','age_18_greater']].sum())

Total enrolments by age group:
age_0_5           3496865
age_5_17          1703882
age_18_greater     165950
dtype: int64